export const services = [
  {
    id: "tarot-quick",
    type: "tarot",
    name_en: "Quick Tarot Reading",
    name_zh: "快速塔罗解读",
    slug: "tarot-quick",
    description: "Get quick insights on a specific question with a 3-card spread. Perfect for daily guidance or when you need clarity fast.",
    short_description: "3-card spread for quick insights",
    price_min: 15,
    price_max: 15,
    duration_minutes: 10,
    features: [
      { icon: "clock", title: "10 Minutes", description: "Quick but meaningful session" },
      { icon: "cards", title: "3-Card Spread", description: "Past, Present, Future" },
      { icon: "message", title: "Written Summary", description: "Keep your insights forever" },
    ],
    requirements: ["Your specific question", "Optional: Context about your situation"],
    sort_order: 1,
    is_active: true,
    image_url: "/images/tarot-quick.jpg",
  },
  {
    id: "tarot-deep",
    type: "tarot",
    name_en: "Deep Tarot Reading",
    name_zh: "深度塔罗解读",
    slug: "tarot-deep",
    description: "A comprehensive 20-minute session with Celtic Cross spread for deep insights into complex situations. Our most popular service.",
    short_description: "Celtic Cross spread for deep insights",
    price_min: 25,
    price_max: 25,
    duration_minutes: 20,
    features: [
      { icon: "clock", title: "20 Minutes", description: "In-depth exploration" },
      { icon: "cards", title: "Celtic Cross", description: "10-card comprehensive spread" },
      { icon: "video", title: "Video Session", description: "Face-to-face with your reader" },
      { icon: "document", title: "Detailed Report", description: "PDF with card meanings" },
    ],
    requirements: ["Your specific question or area of focus", "Optional: Birth date for additional insights"],
    sort_order: 2,
    is_active: true,
    image_url: "/images/tarot-deep.jpg",
  },
  {
    id: "astrology-natal",
    type: "astrology",
    name_en: "Natal Chart Reading",
    name_zh: "出生星盘解读",
    slug: "astrology-natal",
    description: "Discover your cosmic blueprint with a personalized birth chart analysis. Understand your personality, strengths, and life path.",
    short_description: "Personalized birth chart analysis",
    price_min: 45,
    price_max: 55,
    duration_minutes: 35,
    features: [
      { icon: "star", title: "Complete Chart", description: "Sun, Moon, Rising & more" },
      { icon: "video", title: "Video Session", description: "Interactive consultation" },
      { icon: "document", title: "Birth Chart PDF", description: "Your complete chart" },
      { icon: "calendar", title: "12-Month Forecast", description: "Key dates ahead" },
    ],
    requirements: ["Exact birth date", "Exact birth time", "Birth location (city, country)"],
    sort_order: 3,
    is_active: true,
    image_url: "/images/astrology-natal.jpg",
  },
  {
    id: "bazi-basic",
    type: "bazi",
    name_en: "Bazi Life Reading",
    name_zh: "八字命盘分析",
    slug: "bazi-basic",
    description: "Unlock the secrets of your destiny with authentic Chinese Four Pillars astrology. Understand your life path, strengths, and opportunities.",
    short_description: "Chinese Four Pillars astrology",
    price_min: 60,
    price_max: 60,
    duration_minutes: 45,
    features: [
      { icon: "scroll", title: "Complete Analysis", description: "Day, Month, Year, Hour pillars" },
      { icon: "balance", title: "Five Elements", description: "Your elemental balance" },
      { icon: "video", title: "Video Session", description: "Personal consultation" },
      { icon: "document", title: "Detailed Report", description: "Written analysis included" },
    ],
    requirements: ["Exact birth date", "Exact birth time", "Birth location", "Gender"],
    sort_order: 4,
    is_active: true,
    image_url: "/images/bazi-basic.jpg",
  },
  {
    id: "fengshui-home",
    type: "fengshui",
    name_en: "Home Feng Shui Consultation",
    name_zh: "家居风水咨询",
    slug: "fengshui-home",
    description: "Transform your living space with ancient Feng Shui wisdom. Optimize your home's energy flow for health, wealth, and relationships.",
    short_description: "Optimize your home's energy flow",
    price_min: 120,
    price_max: 150,
    duration_minutes: 60,
    features: [
      { icon: "home", title: "Space Analysis", description: "Room-by-room assessment" },
      { icon: "compass", title: "Bagua Mapping", description: "Energy center identification" },
      { icon: "video", title: "Video Walkthrough", description: "Guided consultation" },
      { icon: "document", title: "Action Plan", description: "Step-by-step recommendations" },
    ],
    requirements: ["Floor plan or video tour of your home", "Birth dates of residents", "Specific areas of concern"],
    sort_order: 5,
    is_active: true,
    image_url: "/images/fengshui-home.jpg",
  },
  {
    id: "qimen-timing",
    type: "qimen",
    name_en: "Qi Men Dun Jia - Timing Analysis",
    name_zh: "奇门遁甲 - 择时决策",
    slug: "qimen-timing",
    description: "Harness the ancient Chinese art of Qi Men Dun Jia to determine the most auspicious timing for important decisions, business ventures, investments, and life events.",
    short_description: "Strategic timing for success",
    price_min: 80,
    price_max: 100,
    duration_minutes: 40,
    features: [
      { icon: "clock", title: "Timing Analysis", description: "Best dates and hours for action" },
      { icon: "map", title: "Directional Energy", description: "Optimal directions for success" },
      { icon: "compass", title: "Strategic Guidance", description: "Hidden opportunities revealed" },
      { icon: "document", title: "Written Report", description: "Detailed timing recommendations" },
    ],
    requirements: ["Your specific goal or decision", "Proposed timeframe", "Birth date for personalization"],
    sort_order: 6,
    is_active: true,
    image_url: "/images/qimen-timing.jpg",
  },
  {
    id: "liuyao-divination",
    type: "liuyao",
    name_en: "Liu Yao Divination",
    name_zh: "六爻占卜",
    slug: "liuyao-divination",
    description: "Consult the ancient Chinese Liu Yao (Six Lines) divination system for precise answers to specific questions about relationships, career, investments, and life decisions.",
    short_description: "Precise answers to your questions",
    price_min: 45,
    price_max: 55,
    duration_minutes: 30,
    features: [
      { icon: "coins", title: "Coin Casting", description: "Traditional casting method" },
      { icon: "scroll", title: "Hexagram Reading", description: "Six-line analysis" },
      { icon: "balance", title: "Yes/No Clarity", description: "Clear direction for decisions" },
      { icon: "video", title: "Video Session", description: "Interactive consultation" },
    ],
    requirements: ["One specific question", "Context about your situation", "Optional: Birth date"],
    sort_order: 7,
    is_active: true,
    image_url: "/images/liuyao-divination.jpg",
  },
];

export const masters = [
  {
    id: "zhang-yihua",
    user_id: "user-zhang-yihua",
    display_name: "Master Zhang Yihua",
    display_nameCn: "张易桦师傅",
    tagline: "Revealing the unseen patterns of timing and destiny",
    taglineCn: "揭露时空能量学的密码，通过决策学来选择正确的风向",
    bio: "Master Zhang Yihua has 8 years of professional experience in Chinese metaphysics and traditional divination. He specializes in Qi Men Dun Jia and Liu Yao divination, two ancient systems used to analyze timing, opportunities, and hidden influences in life events. Through his readings, Master Zhang helps clients gain clarity in areas such as career decisions, relationships, and personal life direction. His consultations combine traditional wisdom with practical insights, offering thoughtful and grounded guidance.",
    bioCn: "张易桦师傅拥有8年中华玄学和传统占卜的专业经验。他专注于奇门遁甲和六爻占卜，这两种古老系统用于分析时机、机遇和人生事件中的隐藏影响。通过他的解读，张师傅帮助客户在职业决策、人际关系和个人生活方向等领域获得清晰认识。他的咨询结合传统智慧与实践洞察，提供深思熟虑且脚踏实地的指导。",
    avatar_url: "/masters/master_zhang_yihua.jpg",
    specialties: ["qimen", "liuyao"],
    specialtiesCn: ["奇门遁甲", "六爻占卜"],
    languages: ["en", "zh"],
    experience_years: 8,
    certifications: [
      { name: "Qi Men Dun Jia Practitioner", issuer: "Chinese Metaphysics Institute", year: 2018 },
      { name: "Liu Yao Divination Certificate", issuer: "Traditional Divination Association", year: 2019 },
    ],
    is_verified: true,
    verification_status: "approved",
    base_price_tier: "standard",
    rating_average: 4.9,
    rating_count: 35,
    completed_sessions: 680,
    timezone: "Asia/Shanghai",
    is_active: true,
  },
  {
    id: "wu-yang",
    user_id: "user-wu-yang",
    display_name: "Master Wu Yang",
    display_nameCn: "戊阳师傅",
    tagline: "Align your path with the flow of cosmic energy",
    taglineCn: "顺应宇宙能量之流，调整您的人生道路",
    bio: "Master Wu Yang has over 12 years of experience practicing Chinese metaphysics. He focuses on BaZi (Four Pillars of Destiny) analysis and Feng Shui consultation, helping clients understand their life patterns and environmental energy. By analyzing a person's birth chart and surroundings, Master Wu provides guidance on career development, financial opportunities, and personal balance. His goal is to help clients align their actions with favorable timing and energy.",
    bioCn: "戊阳师傅拥有超过12年的中华玄学实践经验。他专注于八字（四柱命理）分析和风水咨询，帮助客户理解他们的人生轨迹和环境能量。通过分析个人的生辰八字和周围环境，戊师傅为职业发展、财务机遇和个人平衡提供指导。他的目标是帮助客户在有利时机和能量下采取行动。",
    avatar_url: "/masters/master_wu_yang.jpg",
    specialties: ["bazi", "fengshui"],
    specialtiesCn: ["八字命理", "风水咨询"],
    languages: ["en", "zh"],
    experience_years: 12,
    certifications: [
      { name: "Certified BaZi Master", issuer: "International Chinese Metaphysics Association", year: 2015 },
      { name: "Feng Shui Consultant Certificate", issuer: "Asian Feng Shui Guild", year: 2017 },
    ],
    is_verified: true,
    verification_status: "approved",
    base_price_tier: "premium",
    rating_average: 4.9,
    rating_count: 28,
    completed_sessions: 1120,
    timezone: "Asia/Shanghai",
    is_active: true,
  },
  {
    id: "master-luna",
    user_id: "user-master-luna",
    display_name: "Master Luna",
    display_nameCn: "卢娜师傅",
    tagline: "Seeing what your heart already knows, and what lies ahead",
    taglineCn: "看见您内心已知的一切，以及前方的道路",
    bio: "I use tarot as a mirror to reveal what is hidden beneath the surface — your emotions, your patterns, and the energy surrounding your path. Whether you're facing uncertainty in love, career decisions, or life direction, my readings are designed to bring clarity, not confusion. My approach is intuitive, honest, and deeply personal — helping you reconnect with your inner truth and move forward with confidence.",
    bioCn: "我将塔罗视为一面镜子，揭示隐藏在表面之下的一切——您的情感、您的模式，以及围绕您道路的能量。无论您面临爱情、职业决策还是人生方向的不确定性，我的解读旨在带来清晰而非困惑。我的方法是直观的、诚实的、且非常个人化的——帮助您重新与内在真理连接，并自信地前行。",
    avatar_url: "/masters/master_luna.jpg",
    specialties: ["tarot", "spiritual"],
    specialtiesCn: ["塔罗占卜", "灵性探索"],
    languages: ["en", "zh"],
    experience_years: 8,
    certifications: [
      { name: "Certified Tarot Reader", issuer: "Tarot Certification Board", year: 2022 },
    ],
    is_verified: true,
    verification_status: "approved",
    base_price_tier: "standard",
    rating_average: 4.9,
    rating_count: 24,
    completed_sessions: 850,
    timezone: "America/Los_Angeles",
    is_active: true,
  },
  {
    id: "master-lin",
    user_id: "user-master-lin",
    display_name: "Master Lin",
    display_nameCn: "林师傅",
    tagline: "Clarity, balance, and direction for your life path",
    taglineCn: "为您的人生道路提供清晰、平衡与方向",
    bio: "I specialize in helping you understand the deeper structure of your life — your strengths, timing, and opportunities. Through Bazi and Feng Shui, I provide practical and grounded insights that guide your decisions in career, relationships, and personal growth. My readings are clear, structured, and focused on long-term direction.",
    bioCn: "我专注于帮助您理解生命的深层结构——您的优势、时机和机遇。通过八字和风水，我提供务实而扎实的见解，指导您在职业、人际关系和个人成长方面的决策。我的解读清晰、有条理，并专注于长期方向。",
    avatar_url: "/masters/master_lin.jpg",
    specialties: ["bazi", "fengshui"],
    specialtiesCn: ["八字分析", "风水", "人生道路指导"],
    languages: ["en", "zh"],
    experience_years: 10,
    certifications: [
      { name: "Certified BaZi Master", issuer: "Chinese Metaphysics Institute", year: 2016 },
      { name: "Feng Shui Practitioner", issuer: "International Feng Shui Association", year: 2018 },
    ],
    is_verified: true,
    verification_status: "approved",
    base_price_tier: "standard",
    rating_average: 4.8,
    rating_count: 328,
    completed_sessions: 920,
    timezone: "Asia/Shanghai",
    is_active: true,
  },
  {
    id: "master-han",
    user_id: "user-master-han",
    display_name: "Master Han",
    display_nameCn: "韩师傅",
    tagline: "Clear guidance, in a way that feels simple and personal",
    taglineCn: "以简单个人化的方式提供清晰指引",
    bio: "I believe that understanding your life path shouldn't feel complicated or distant. My readings focus on making Bazi simple, clear, and directly useful for your everyday decisions — whether it's career choices, relationships, or timing. Many people come to me when they feel unsure or stuck. I help break things down in a way that feels natural, practical, and easy to follow.",
    bioCn: "我相信理解您的人生道路不应该感到复杂或遥远。我的解读专注于让八字变得简单、清晰，并对您的日常决策直接有用——无论是职业选择、人际关系还是时机把握。许多人在感到不确定或困惑时会来找我。我以一种自然、务实、易于理解的方式来帮助您理清思路。",
    avatar_url: "/masters/master_han.jpg",
    specialties: ["bazi"],
    specialtiesCn: ["八字解读", "人生方向", "时机指导"],
    languages: ["en", "zh"],
    experience_years: 6,
    certifications: [
      { name: "BaZi Divination Certificate", issuer: "Traditional Chinese Metaphysics Association", year: 2020 },
    ],
    is_verified: true,
    verification_status: "approved",
    base_price_tier: "standard",
    rating_average: 4.7,
    rating_count: 172,
    completed_sessions: 540,
    timezone: "Asia/Shanghai",
    is_active: true,
  },
  {
    id: "master-elena",
    user_id: "user-master-elena",
    display_name: "Master Elena",
    display_nameCn: "艾琳娜师傅",
    tagline: "Insight, clarity, and emotional truth through tarot",
    taglineCn: "通过塔罗获得洞察、清晰与情感真相",
    bio: "I use tarot to help you understand what you're feeling, what the other person feels, and where things are heading. Whether you're dealing with love uncertainty, emotional confusion, or life decisions, my readings are intuitive, honest, and focused on clarity. Many people come to me when they feel lost or overwhelmed — I help them find direction and peace of mind.",
    bioCn: "我使用塔罗来帮助您理解自己的感受、对方的感受，以及事情的发展方向。无论您是在处理爱情的不确定性、情感的困惑，还是人生决策，我的解读都是直观的、诚实的，并专注于清晰。许多人在感到迷失或不知所措时会来找我——我帮助他们找到方向和内心的平静。",
    avatar_url: "/masters/master_elena.jpg",
    specialties: ["tarot"],
    specialtiesCn: ["爱情关系", "情感清晰", "未来洞察", "塔罗解读"],
    languages: ["en"],
    experience_years: 7,
    certifications: [
      { name: "Certified Tarot Reader", issuer: "Tarot Certification Board", year: 2019 },
      { name: "Relationship Counseling Diploma", issuer: "Institute of Intuitive Studies", year: 2021 },
    ],
    is_verified: true,
    verification_status: "approved",
    base_price_tier: "standard",
    rating_average: 4.7,
    rating_count: 301,
    completed_sessions: 780,
    timezone: "America/Los_Angeles",
    is_active: true,
  },
];

export const reviews = [
  // ========== Master Lin (8 reviews) ==========
  {
    id: "review-lin-1",
    order_id: "order-lin-1",
    user_id: "user-lin-1",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "八字看出事业转机",
    content: "林师傅帮我分析八字，说我今年下半年有事业转机的运势，建议我在9月份主动争取新项目。当时还将信将疑，没想到10月真的有新项目空缺，我主动请缨后顺利拿下，现在已经成为部门负责人了。",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-10T14:30:00Z",
    user: { full_name: "王先生", avatar_url: null },
  },
  {
    id: "review-lin-2",
    order_id: "order-lin-2",
    user_id: "user-lin-2",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "风水调理改善家庭关系",
    content: "家里一直不和，夫妻感情也很紧张。林师傅上门看了风水，指出厨房和卧室的布局问题。按他的建议调整后，家里的氛围真的变了，现在和太太沟通顺畅多了，孩子也更听话。感谢林师傅！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-08T09:15:00Z",
    user: { full_name: "陈女士", avatar_url: null },
  },
  {
    id: "review-lin-3",
    order_id: "order-lin-3",
    user_id: "user-lin-3",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Career crossroads made clear",
    content: "I was stuck between two job offers and couldn't decide. Master Lin used Bazi analysis to help me understand my strengths and the timing of each opportunity. His insights helped me choose the right path - now I'm thriving in a role that truly fits me.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-28T16:45:00Z",
    user: { full_name: "Michael T.", avatar_url: null },
  },
  {
    id: "review-lin-4",
    order_id: "order-lin-4",
    user_id: "user-lin-4",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 4,
    value_rating: 5,
    title: "Accurate prediction about family matters",
    content: "Master Lin predicted a family dispute before it happened and gave me advice on how to navigate it peacefully. When the situation arose exactly as he described, I was prepared and handled it well. His foresight is remarkable.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-20T11:20:00Z",
    user: { full_name: "匿名用户", avatar_url: null },
  },
  {
    id: "review-lin-5",
    order_id: "order-lin-5",
    user_id: "user-lin-5",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Feng Shui transformation at home",
    content: "After Master Lin's Feng Shui consultation, I rearranged my home office according to his recommendations. Within a month, I received a promotion and my stress levels decreased significantly. The energy shift was palpable!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-12T11:00:00Z",
    user: { full_name: "Emily R.", avatar_url: null },
  },
  {
    id: "review-lin-6",
    order_id: "order-lin-6",
    user_id: "user-lin-6",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Helped me understand my life's direction",
    content: "I've always felt lost about my purpose. Master Lin's reading didn't just tell me what would happen - he helped me understand why certain patterns kept repeating in my life. His practical advice on timing and direction has been invaluable.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-10T13:00:00Z",
    user: { full_name: "David K.", avatar_url: null },
  },
  {
    id: "review-lin-7",
    order_id: "order-lin-7",
    user_id: "user-lin-7",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Real estate timing was perfect",
    content: "I consulted Master Lin about when to list my property. He gave me a specific window of time. I followed his advice and received multiple offers within the first week, selling above asking price. The timing was absolutely perfect!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-05T10:45:00Z",
    user: { full_name: "王小姐", avatar_url: null },
  },
  {
    id: "review-lin-8",
    order_id: "order-lin-8",
    user_id: "user-lin-8",
    master_id: "master-lin",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Good insights on legal matters",
    content: "I had a legal dispute and Master Lin analyzed the energy around the situation. His prediction about the timeline and outcome was accurate. The only reason for 4 stars is that I wish the consultation was a bit longer - there's so much to learn from him.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-28T15:20:00Z",
    user: { full_name: "Robert J.", avatar_url: null },
  },

  // ========== Master Han (8 reviews) ==========
  {
    id: "review-han-1",
    order_id: "order-han-1",
    user_id: "user-han-1",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Simple and clear guidance",
    content: "Master Han has a gift for making complex Bazi concepts easy to understand. He explained my chart in simple terms and gave me practical advice I could actually use. Finally, a reader who doesn't confuse me with jargon!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-11T10:30:00Z",
    user: { full_name: "Lisa M.", avatar_url: null },
  },
  {
    id: "review-han-2",
    order_id: "order-han-2",
    user_id: "user-han-2",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Helped me when I felt stuck",
    content: "I was at a crossroads in my career and didn't know which direction to take. Master Han's reading gave me clarity about my strengths and the best timing for change. His guidance was practical and easy to follow. Highly recommend!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-05T14:15:00Z",
    user: { full_name: "Jason P.", avatar_url: null },
  },
  {
    id: "review-han-3",
    order_id: "order-han-3",
    user_id: "user-han-3",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Relationship timing was spot on",
    content: "Master Han predicted when I would meet someone significant and described the type of person they would be. He was right on both counts! His timing predictions are incredibly accurate.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-25T09:30:00Z",
    user: { full_name: "Amanda L.", avatar_url: null },
  },
  {
    id: "review-han-4",
    order_id: "order-han-4",
    user_id: "user-han-4",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Practical and down-to-earth",
    content: "Unlike other readers who speak in riddles, Master Han gives you straight answers. His practical approach helped me make a difficult business decision with confidence. Great value for the price.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-18T16:00:00Z",
    user: { full_name: "Thomas B.", avatar_url: null },
  },
  {
    id: "review-han-5",
    order_id: "order-han-5",
    user_id: "user-han-5",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Life direction clarity",
    content: "I've consulted many readers before, but Master Han's approach is refreshingly simple and personal. He helped me see my life path clearly and gave me actionable steps to take. I feel much more confident about my future now.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-12T13:30:00Z",
    user: { full_name: "Maria G.", avatar_url: null },
  },
  {
    id: "review-han-6",
    order_id: "order-han-6",
    user_id: "user-han-6",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Perfect for beginners",
    content: "This was my first Bazi reading and Master Han made it so accessible. He explained everything in plain English and made sure I understood before moving on. No confusing jargon, just clear insights.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-08T11:15:00Z",
    user: { full_name: "陈先生", avatar_url: null },
  },
  {
    id: "review-han-7",
    order_id: "order-han-7",
    user_id: "user-han-7",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Timely and accurate predictions",
    content: "Master Han predicted a major opportunity in my career with specific timing. When it happened exactly as he said, I was amazed. His ability to read timing is exceptional.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-25T15:45:00Z",
    user: { full_name: "Jennifer & Mark", avatar_url: null },
  },
  {
    id: "review-han-8",
    order_id: "order-han-8",
    user_id: "user-han-8",
    master_id: "master-han",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Helped me find balance",
    content: "Master Han's reading helped me understand my elemental balance and how it affects my daily life. His simple recommendations have made a noticeable difference in my energy levels and mood.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-20T11:30:00Z",
    user: { full_name: "Alexandra P.", avatar_url: null },
  },

  // ========== Master Elena (10 reviews) ==========
  {
    id: "review-elena-1",
    order_id: "order-elena-1",
    user_id: "user-elena-1",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Clarity when I needed it most",
    content: "Master Elena's tarot reading brought tears to my eyes. She saw exactly what I was going through in my relationship and gave me the clarity I needed to make a difficult decision. Her intuition is incredible - she knew things I hadn't even mentioned.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-14T19:30:00Z",
    user: { full_name: "Sophia M.", avatar_url: null },
  },
  {
    id: "review-elena-2",
    order_id: "order-elena-2",
    user_id: "user-elena-2",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Love reading that came true",
    content: "Master Elena predicted I would meet someone significant within three months and described their personality perfectly. I met my current partner exactly six weeks later - the description was spot on! Her readings are truly magical.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-22T16:30:00Z",
    user: { full_name: "Amanda L.", avatar_url: null },
  },
  {
    id: "review-elena-3",
    order_id: "order-elena-3",
    user_id: "user-elena-3",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Emotional truth revealed",
    content: "I was dealing with so much confusion about my relationship. Master Elena's reading helped me understand not just what was happening, but why I was feeling the way I was. Her insights into emotional patterns were eye-opening.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-01T10:45:00Z",
    user: { full_name: "Rachel H.", avatar_url: null },
  },
  {
    id: "review-elena-4",
    order_id: "order-elena-4",
    user_id: "user-elena-4",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Future insight that helped me prepare",
    content: "Master Elena predicted challenges in my relationship before they happened. Instead of panicking, I was able to prepare and navigate them successfully. Her foresight is truly a gift.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-18T11:00:00Z",
    user: { full_name: "Michael R.", avatar_url: null },
  },
  {
    id: "review-elena-5",
    order_id: "order-elena-5",
    user_id: "user-elena-5",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Honest and compassionate",
    content: "Master Elena doesn't sugarcoat things, but she delivers even difficult truths with compassion. Her honest approach helped me face some uncomfortable realities about my relationship that I needed to see.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-10T15:20:00Z",
    user: { full_name: "Jessica T.", avatar_url: null },
  },
  {
    id: "review-elena-6",
    order_id: "order-elena-6",
    user_id: "user-elena-6",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Guidance through heartbreak",
    content: "After a painful breakup, I felt completely lost. Master Elena's reading helped me process my emotions and understand the lessons in this experience. Her compassionate approach brought me peace when I needed it most.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-05T13:45:00Z",
    user: { full_name: "Andrew P.", avatar_url: null },
  },
  {
    id: "review-elena-7",
    order_id: "order-elena-7",
    user_id: "user-elena-7",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Career and love balance",
    content: "I was struggling to balance my career ambitions with my relationship. Master Elena's reading helped me see how these areas of my life interact and gave me practical guidance for finding harmony.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-28T10:30:00Z",
    user: { full_name: "Christina B.", avatar_url: null },
  },
  {
    id: "review-elena-8",
    order_id: "order-elena-8",
    user_id: "user-elena-8",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Monthly guidance keeps me grounded",
    content: "I book a session with Master Elena every month. Her readings help me navigate the ups and downs of my relationships with clarity and grace. She's become an essential part of my self-care routine.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-22T17:00:00Z",
    user: { full_name: "Natalie S.", avatar_url: null },
  },
  {
    id: "review-elena-9",
    order_id: "order-elena-9",
    user_id: "user-elena-9",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Empowering and insightful",
    content: "Unlike other readings that left me feeling anxious, Master Elena's session left me feeling empowered. She helped me see my own strengths and the opportunities ahead in my love life.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-15T12:15:00Z",
    user: { full_name: "Brian W.", avatar_url: null },
  },
  {
    id: "review-elena-10",
    order_id: "order-elena-10",
    user_id: "user-elena-10",
    master_id: "master-elena",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Deep emotional insights",
    content: "Master Elena goes deep into the emotional aspects of situations. Her reading helped me understand not just what was happening externally, but what was going on internally. Wish the session could have been longer!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-10T14:00:00Z",
    user: { full_name: "Diana K.", avatar_url: null },
  },

  // ========== Master Zhang Yihua (6 reviews) ==========
  {
    id: "review-zhang-1",
    order_id: "order-zhang-1",
    user_id: "user-zhang-1",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Qi Men Dun Jia guidance led to investment success",
    content: "非常感谢张师傅，经过你的帮助后拿到了10万的投资资金，虽然跟预想金额有点出入，但是足够了，过程也是挺顺畅。",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-08T14:30:00Z",
    user: { full_name: "王先生", avatar_url: null },
  },
  {
    id: "review-zhang-2",
    order_id: "order-zhang-2",
    user_id: "user-zhang-2",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Six Lines divination for career decision",
    content: "I was considering a job change but was uncertain. Master Zhang used Liu Yao divination to analyze the situation. His reading revealed hidden factors I hadn't considered and helped me make the right choice. Very grateful!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-25T10:15:00Z",
    user: { full_name: "Sarah Chen", avatar_url: null },
  },
  {
    id: "review-zhang-3",
    order_id: "order-zhang-3",
    user_id: "user-zhang-3",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 4,
    value_rating: 5,
    title: "Relationship clarity through divination",
    content: "感情问题困扰我很久，张师傅通过六爻占卜点出了关键所在。他不仅指出了问题的根源，还给出了具体的化解建议。现在我和伴侣的关系明显改善，非常感谢！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-14T16:00:00Z",
    user: { full_name: "李女士", avatar_url: null },
  },
  {
    id: "review-zhang-4",
    order_id: "order-zhang-4",
    user_id: "user-zhang-4",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Investment timing guidance",
    content: "Master Zhang analyzed the timing for a property investment using Qi Men Dun Jia. His prediction about market conditions was accurate, and I was able to buy at the right moment. Saved me a significant amount of money.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-28T09:30:00Z",
    user: { full_name: "David Wu", avatar_url: null },
  },
  {
    id: "review-zhang-5",
    order_id: "order-zhang-5",
    user_id: "user-zhang-5",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Business partnership analysis",
    content: "考虑和一位合伙人共同创业，张师傅通过奇门遁甲分析了双方的命理契合度。他指出的潜在问题后来确实出现了，幸亏提前有了准备。专业、准确、值得信任！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-15T13:45:00Z",
    user: { full_name: "陈先生", avatar_url: null },
  },
  {
    id: "review-zhang-6",
    order_id: "order-zhang-6",
    user_id: "user-zhang-6",
    master_id: "zhang-yihua",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Clear and methodical approach",
    content: "Master Zhang's approach to divination is very systematic. He explains the hexagrams and their meanings clearly, making the ancient wisdom accessible. His predictions have been consistently accurate in my experience.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-08T11:20:00Z",
    user: { full_name: "Emma Thompson", avatar_url: null },
  },

  // ========== Master Wu Yang (6 reviews) ==========
  {
    id: "review-wu-1",
    order_id: "order-wu-1",
    user_id: "user-wu-1",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "BaZi reading transformed my career",
    content: "戊阳师傅的八字分析让我对自己有了全新的认识。他指出了我命中适合的发展方向，以及需要避开的时期。按照他的建议调整职业规划后，事业明显顺利了许多。12年经验果然不同凡响！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-05T15:30:00Z",
    user: { full_name: "张先生", avatar_url: null },
  },
  {
    id: "review-wu-2",
    order_id: "order-wu-2",
    user_id: "user-wu-2",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Feng Shui consultation for home",
    content: "We were experiencing health issues and financial difficulties. Master Wu's Feng Shui consultation revealed energy blockages in our home. After implementing his recommendations, the atmosphere improved dramatically within weeks.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-20T10:00:00Z",
    user: { full_name: "Jennifer Liu", avatar_url: null },
  },
  {
    id: "review-wu-3",
    order_id: "order-wu-3",
    user_id: "user-wu-3",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Wealth and prosperity guidance",
    content: "戊阳师傅通过八字分析了我的财运走势，并给出了具体的改善建议。他建议我调整办公桌方位和家中财位布置，效果非常明显。最近几个月业绩提升了不少！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-08T14:15:00Z",
    user: { full_name: "刘女士", avatar_url: null },
  },
  {
    id: "review-wu-4",
    order_id: "order-wu-4",
    user_id: "user-wu-4",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Accurate health predictions",
    content: "Master Wu predicted a health concern in my BaZi chart before it manifested. His early warning allowed me to take preventive measures. His understanding of the connection between destiny and health is remarkable.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-25T09:45:00Z",
    user: { full_name: "Michael Chang", avatar_url: null },
  },
  {
    id: "review-wu-5",
    order_id: "order-wu-5",
    user_id: "user-wu-5",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 4,
    value_rating: 5,
    title: "Family harmony through Feng Shui",
    content: "家里一直有不和谐的气氛，戊阳师傅来看了风水后，指出了几个关键问题。调整之后，家庭关系明显改善，孩子们也更听话了。风水真的有科学依据！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-12T16:30:00Z",
    user: { full_name: "黄太太", avatar_url: null },
  },
  {
    id: "review-wu-6",
    order_id: "order-wu-6",
    user_id: "user-wu-6",
    master_id: "wu-yang",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Comprehensive life path analysis",
    content: "Master Wu provided a thorough BaZi analysis covering career, relationships, and health. His 12+ years of experience shows in the depth of his insights. The consultation was well worth the investment.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-05T11:00:00Z",
    user: { full_name: "Robert Zhang", avatar_url: null },
  },

  // ========== Master Luna (6 reviews) ==========
  {
    id: "review-luna-1",
    order_id: "order-luna-1",
    user_id: "user-luna-1",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Tarot revealed my true feelings",
    content: "I was confused about a relationship and Master Luna's tarot reading helped me see what my heart already knew but my mind was avoiding. Her intuitive insights were spot on and helped me make a decision I was avoiding.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-12T19:00:00Z",
    user: { full_name: "Amanda S.", avatar_url: null },
  },
  {
    id: "review-luna-2",
    order_id: "order-luna-2",
    user_id: "user-luna-2",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Career clarity through the cards",
    content: "Master Luna used tarot to help me understand my career path. The reading revealed opportunities I hadn't considered and confirmed my instincts about leaving a toxic work environment. Now I'm in a much better place professionally.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-28T15:30:00Z",
    user: { full_name: "James Chen", avatar_url: null },
  },
  {
    id: "review-luna-3",
    order_id: "order-luna-3",
    user_id: "user-luna-3",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Guidance during a difficult transition",
    content: "当我面临人生重大转折时，卢娜师傅的塔罗解读给了我希望和方向。她看到的不仅是当前的困难，还有未来的可能性。她的解读温柔而有力，让我重新找回了前进的勇气。",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-15T20:00:00Z",
    user: { full_name: "林小姐", avatar_url: null },
  },
  {
    id: "review-luna-4",
    order_id: "order-luna-4",
    user_id: "user-luna-4",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Monthly readings keep me aligned",
    content: "I've been having monthly sessions with Master Luna for half a year now. Her tarot readings help me stay aligned with my true path and navigate challenges with grace. She's like a spiritual compass in my life.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-01T18:30:00Z",
    user: { full_name: "Michelle Wang", avatar_url: null },
  },
  {
    id: "review-luna-5",
    order_id: "order-luna-5",
    user_id: "user-luna-5",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Love and relationship insights",
    content: "卢娜师傅帮我看清了一段纠结很久的感情。她的塔罗牌不仅显示了现状，还指出了我需要学习的课题。现在我明白了什么是真正适合我的关系，感谢她的指引！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-20T14:00:00Z",
    user: { full_name: "周女士", avatar_url: null },
  },
  {
    id: "review-luna-6",
    order_id: "order-luna-6",
    user_id: "user-luna-6",
    master_id: "master-luna",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Intuitive and empowering",
    content: "Master Luna has a rare gift of combining intuition with practical guidance. Her readings don't just tell you what's happening - they empower you to take control of your destiny. Highly recommended for anyone seeking clarity.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-10T16:45:00Z",
    user: { full_name: "Thomas Lee", avatar_url: null },
  },
];