export const reviews = [
  // ========== Master Lin (8 reviews) ==========
  {
    id: "review-lin-1",
    order_id: "order-lin-1",
    user_id: "user-lin-1",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Investment guidance that actually worked",
    content: "非常感谢你，我经过你的帮助后拿到了10万的投资资金，虽然跟预想金额有点出入，但是足够了，过程也是挺顺畅。林师傅的八字分析帮我在最合适的时间提交了申请，真的太准了！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-10T14:30:00Z",
    user: { full_name: "刘先生", avatar_url: null },
  },
  {
    id: "review-lin-2",
    order_id: "order-lin-2",
    user_id: "user-lin-2",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Found my soulmate with his guidance",
    content: "师傅没要我任何东西，直接算出来我的感情问题和交往朋友的方法，非常精准，后续也帮我更好的找到了正缘！非常感谢师傅。八字分析真的太神奇了，说的每一点都对应上了。",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-08T09:15:00Z",
    user: { full_name: "陈女士", avatar_url: null },
  },
  {
    id: "review-lin-3",
    order_id: "order-lin-3",
    user_id: "user-lin-3",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Career crossroads made clear",
    content: "I was stuck between two job offers and couldn't decide. Master Lin used Bazi analysis to help me understand my strengths and the timing of each opportunity. His insights helped me choose the right path - now I'm thriving in a role that truly fits me.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-28T16:45:00Z",
    user: { full_name: "Michael T.", avatar_url: null },
  },
  {
    id: "review-lin-4",
    order_id: "order-lin-4",
    user_id: "user-lin-4",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 4,
    value_rating: 5,
    title: "Accurate prediction about family matters",
    content: "Master Lin predicted a family dispute before it happened and gave me advice on how to navigate it peacefully. When the situation arose exactly as he described, I was prepared and handled it well. His foresight is remarkable.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-20T11:20:00Z",
    user: { full_name: "匿名用户", avatar_url: null },
  },
  {
    id: "review-lin-5",
    order_id: "order-lin-5",
    user_id: "user-lin-5",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Feng Shui transformation at home",
    content: "After Master Lin's Feng Shui consultation, I rearranged my home office according to his recommendations. Within a month, I received a promotion and my stress levels decreased significantly. The energy shift was palpable!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-12T11:00:00Z",
    user: { full_name: "Emily R.", avatar_url: null },
  },
  {
    id: "review-lin-6",
    order_id: "order-lin-6",
    user_id: "user-lin-6",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Helped me understand my life's direction",
    content: "I've always felt lost about my purpose. Master Lin's reading didn't just tell me what would happen - he helped me understand why certain patterns kept repeating in my life. His practical advice on timing and direction has been invaluable.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-10T13:00:00Z",
    user: { full_name: "David K.", avatar_url: null },
  },
  {
    id: "review-lin-7",
    order_id: "order-lin-7",
    user_id: "user-lin-7",
    master_id: "master-lin",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Real estate timing was perfect",
    content: "I consulted Master Lin about when to list my property. He gave me a specific window of time. I followed his advice and received multiple offers within the first week, selling above asking price. The timing was absolutely perfect!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-05T10:45:00Z",
    user: { full_name: "王小姐", avatar_url: null },
  },
  {
    id: "review-lin-8",
    order_id: "order-lin-8",
    user_id: "user-lin-8",
    master_id: "master-lin",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Good insights on legal matters",
    content: "I had a legal dispute and Master Lin analyzed the energy around the situation. His prediction about the timeline and outcome was accurate. The only reason for 4 stars is that I wish the consultation was a bit longer - there's so much to learn from him.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-28T15:20:00Z",
    user: { full_name: "Robert J.", avatar_url: null },
  },

  // ========== Master Han (8 reviews) ==========
  {
    id: "review-han-1",
    order_id: "order-han-1",
    user_id: "user-han-1",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Simple and clear guidance",
    content: "Master Han has a gift for making complex Bazi concepts easy to understand. He explained my chart in simple terms and gave me practical advice I could actually use. Finally, a reader who doesn't confuse me with jargon!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-11T10:30:00Z",
    user: { full_name: "Lisa M.", avatar_url: null },
  },
  {
    id: "review-han-2",
    order_id: "order-han-2",
    user_id: "user-han-2",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Helped me when I felt stuck",
    content: "I was at a crossroads in my career and didn't know which direction to take. Master Han's reading gave me clarity about my strengths and the best timing for change. His guidance was practical and easy to follow. Highly recommend!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-05T14:15:00Z",
    user: { full_name: "Jason P.", avatar_url: null },
  },
  {
    id: "review-han-3",
    order_id: "order-han-3",
    user_id: "user-han-3",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Relationship timing was spot on",
    content: "Master Han predicted when I would meet someone significant and described the type of person they would be. He was right on both counts! His timing predictions are incredibly accurate.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-25T09:30:00Z",
    user: { full_name: "Amanda L.", avatar_url: null },
  },
  {
    id: "review-han-4",
    order_id: "order-han-4",
    user_id: "user-han-4",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Practical and down-to-earth",
    content: "Unlike other readers who speak in riddles, Master Han gives you straight answers. His practical approach helped me make a difficult business decision with confidence. Great value for the price.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-18T16:00:00Z",
    user: { full_name: "Thomas B.", avatar_url: null },
  },
  {
    id: "review-han-5",
    order_id: "order-han-5",
    user_id: "user-han-5",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Life direction clarity",
    content: "I've consulted many readers before, but Master Han's approach is refreshingly simple and personal. He helped me see my life path clearly and gave me actionable steps to take. I feel much more confident about my future now.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-12T13:30:00Z",
    user: { full_name: "Maria G.", avatar_url: null },
  },
  {
    id: "review-han-6",
    order_id: "order-han-6",
    user_id: "user-han-6",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Perfect for beginners",
    content: "This was my first Bazi reading and Master Han made it so accessible. He explained everything in plain English and made sure I understood before moving on. No confusing jargon, just clear insights.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-08T11:15:00Z",
    user: { full_name: "陈先生", avatar_url: null },
  },
  {
    id: "review-han-7",
    order_id: "order-han-7",
    user_id: "user-han-7",
    master_id: "master-han",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Timely and accurate predictions",
    content: "Master Han predicted a major opportunity in my career with specific timing. When it happened exactly as he said, I was amazed. His ability to read timing is exceptional.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-25T15:45:00Z",
    user: { full_name: "Jennifer & Mark", avatar_url: null },
  },
  {
    id: "review-han-8",
    order_id: "order-han-8",
    user_id: "user-han-8",
    master_id: "master-han",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Helped me find balance",
    content: "Master Han's reading helped me understand my elemental balance and how it affects my daily life. His simple recommendations have made a noticeable difference in my energy levels and mood.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-20T11:30:00Z",
    user: { full_name: "Alexandra P.", avatar_url: null },
  },

  // ========== Master Elena (10 reviews) ==========
  {
    id: "review-elena-1",
    order_id: "order-elena-1",
    user_id: "user-elena-1",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Clarity when I needed it most",
    content: "Master Elena's tarot reading brought tears to my eyes. She saw exactly what I was going through in my relationship and gave me the clarity I needed to make a difficult decision. Her intuition is incredible - she knew things I hadn't even mentioned.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-14T19:30:00Z",
    user: { full_name: "Sophia M.", avatar_url: null },
  },
  {
    id: "review-elena-2",
    order_id: "order-elena-2",
    user_id: "user-elena-2",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Love reading that came true",
    content: "Master Elena predicted I would meet someone significant within three months and described their personality perfectly. I met my current partner exactly six weeks later - the description was spot on! Her readings are truly magical.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-22T16:30:00Z",
    user: { full_name: "Amanda L.", avatar_url: null },
  },
  {
    id: "review-elena-3",
    order_id: "order-elena-3",
    user_id: "user-elena-3",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Emotional truth revealed",
    content: "I was dealing with so much confusion about my relationship. Master Elena's reading helped me understand not just what was happening, but why I was feeling the way I was. Her insights into emotional patterns were eye-opening.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-01T10:45:00Z",
    user: { full_name: "Rachel H.", avatar_url: null },
  },
  {
    id: "review-elena-4",
    order_id: "order-elena-4",
    user_id: "user-elena-4",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Future insight that helped me prepare",
    content: "Master Elena predicted challenges in my relationship before they happened. Instead of panicking, I was able to prepare and navigate them successfully. Her foresight is truly a gift.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-18T11:00:00Z",
    user: { full_name: "Michael R.", avatar_url: null },
  },
  {
    id: "review-elena-5",
    order_id: "order-elena-5",
    user_id: "user-elena-5",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Honest and compassionate",
    content: "Master Elena doesn't sugarcoat things, but she delivers even difficult truths with compassion. Her honest approach helped me face some uncomfortable realities about my relationship that I needed to see.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-10T15:20:00Z",
    user: { full_name: "Jessica T.", avatar_url: null },
  },
  {
    id: "review-elena-6",
    order_id: "order-elena-6",
    user_id: "user-elena-6",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Guidance through heartbreak",
    content: "After a painful breakup, I felt completely lost. Master Elena's reading helped me process my emotions and understand the lessons in this experience. Her compassionate approach brought me peace when I needed it most.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-05T13:45:00Z",
    user: { full_name: "Andrew P.", avatar_url: null },
  },
  {
    id: "review-elena-7",
    order_id: "order-elena-7",
    user_id: "user-elena-7",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Career and love balance",
    content: "I was struggling to balance my career ambitions with my relationship. Master Elena's reading helped me see how these areas of my life interact and gave me practical guidance for finding harmony.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-28T10:30:00Z",
    user: { full_name: "Christina B.", avatar_url: null },
  },
  {
    id: "review-elena-8",
    order_id: "order-elena-8",
    user_id: "user-elena-8",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Monthly guidance keeps me grounded",
    content: "I book a session with Master Elena every month. Her readings help me navigate the ups and downs of my relationships with clarity and grace. She's become an essential part of my self-care routine.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-22T17:00:00Z",
    user: { full_name: "Natalie S.", avatar_url: null },
  },
  {
    id: "review-elena-9",
    order_id: "order-elena-9",
    user_id: "user-elena-9",
    master_id: "master-elena",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Empowering and insightful",
    content: "Unlike other readings that left me feeling anxious, Master Elena's session left me feeling empowered. She helped me see my own strengths and the opportunities ahead in my love life.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-15T12:15:00Z",
    user: { full_name: "Brian W.", avatar_url: null },
  },
  {
    id: "review-elena-10",
    order_id: "order-elena-10",
    user_id: "user-elena-10",
    master_id: "master-elena",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Deep emotional insights",
    content: "Master Elena goes deep into the emotional aspects of situations. Her reading helped me understand not just what was happening externally, but what was going on internally. Wish the session could have been longer!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-10T14:00:00Z",
    user: { full_name: "Diana K.", avatar_url: null },
  },

  // ========== Master Zhang Yihua (6 reviews) ==========
  {
    id: "review-zhang-1",
    order_id: "order-zhang-1",
    user_id: "user-zhang-1",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Qi Men Dun Jia timing was exact",
    content: "张师傅用奇门遁甲帮我选择了一个重要商务会议的时间，结果谈判出奇顺利，成功签下了合同。他对时机的把握令人惊叹，真正展现了中华玄学的智慧。",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-08T14:30:00Z",
    user: { full_name: "王先生", avatar_url: null },
  },
  {
    id: "review-zhang-2",
    order_id: "order-zhang-2",
    user_id: "user-zhang-2",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Six Lines divination for career decision",
    content: "I was considering a job change but was uncertain. Master Zhang used Liu Yao divination to analyze the situation. His reading revealed hidden factors I hadn't considered and helped me make the right choice. Very grateful!",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-25T10:15:00Z",
    user: { full_name: "Sarah Chen", avatar_url: null },
  },
  {
    id: "review-zhang-3",
    order_id: "order-zhang-3",
    user_id: "user-zhang-3",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 4,
    value_rating: 5,
    title: "Relationship clarity through divination",
    content: "感情问题困扰我很久，张师傅通过六爻占卜点出了关键所在。他不仅指出了问题的根源，还给出了具体的化解建议。现在我和伴侣的关系明显改善，非常感谢！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-14T16:00:00Z",
    user: { full_name: "李女士", avatar_url: null },
  },
  {
    id: "review-zhang-4",
    order_id: "order-zhang-4",
    user_id: "user-zhang-4",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Investment timing guidance",
    content: "Master Zhang analyzed the timing for a property investment using Qi Men Dun Jia. His prediction about market conditions was accurate, and I was able to buy at the right moment. Saved me a significant amount of money.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-28T09:30:00Z",
    user: { full_name: "David Wu", avatar_url: null },
  },
  {
    id: "review-zhang-5",
    order_id: "order-zhang-5",
    user_id: "user-zhang-5",
    master_id: "zhang-yihua",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Business partnership analysis",
    content: "考虑和一位合伙人共同创业，张师傅通过奇门遁甲分析了双方的命理契合度。他指出的潜在问题后来确实出现了，幸亏提前有了准备。专业、准确、值得信任！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-15T13:45:00Z",
    user: { full_name: "陈先生", avatar_url: null },
  },
  {
    id: "review-zhang-6",
    order_id: "order-zhang-6",
    user_id: "user-zhang-6",
    master_id: "zhang-yihua",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Clear and methodical approach",
    content: "Master Zhang's approach to divination is very systematic. He explains the hexagrams and their meanings clearly, making the ancient wisdom accessible. His predictions have been consistently accurate in my experience.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-08T11:20:00Z",
    user: { full_name: "Emma Thompson", avatar_url: null },
  },

  // ========== Master Wu Yang (6 reviews) ==========
  {
    id: "review-wu-1",
    order_id: "order-wu-1",
    user_id: "user-wu-1",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "BaZi reading transformed my career",
    content: "戊阳师傅的八字分析让我对自己有了全新的认识。他指出了我命中适合的发展方向，以及需要避开的时期。按照他的建议调整职业规划后，事业明显顺利了许多。12年经验果然不同凡响！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-05T15:30:00Z",
    user: { full_name: "张先生", avatar_url: null },
  },
  {
    id: "review-wu-2",
    order_id: "order-wu-2",
    user_id: "user-wu-2",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Feng Shui consultation for home",
    content: "We were experiencing health issues and financial difficulties. Master Wu's Feng Shui consultation revealed energy blockages in our home. After implementing his recommendations, the atmosphere improved dramatically within weeks.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-20T10:00:00Z",
    user: { full_name: "Jennifer Liu", avatar_url: null },
  },
  {
    id: "review-wu-3",
    order_id: "order-wu-3",
    user_id: "user-wu-3",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Wealth and prosperity guidance",
    content: "戊阳师傅通过八字分析了我的财运走势，并给出了具体的改善建议。他建议我调整办公桌方位和家中财位布置，效果非常明显。最近几个月业绩提升了不少！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-08T14:15:00Z",
    user: { full_name: "刘女士", avatar_url: null },
  },
  {
    id: "review-wu-4",
    order_id: "order-wu-4",
    user_id: "user-wu-4",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Accurate health predictions",
    content: "Master Wu predicted a health concern in my BaZi chart before it manifested. His early warning allowed me to take preventive measures. His understanding of the connection between destiny and health is remarkable.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-25T09:45:00Z",
    user: { full_name: "Michael Chang", avatar_url: null },
  },
  {
    id: "review-wu-5",
    order_id: "order-wu-5",
    user_id: "user-wu-5",
    master_id: "wu-yang",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 4,
    value_rating: 5,
    title: "Family harmony through Feng Shui",
    content: "家里一直有不和谐的气氛，戊阳师傅来看了风水后，指出了几个关键问题。调整之后，家庭关系明显改善，孩子们也更听话了。风水真的有科学依据！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-12T16:30:00Z",
    user: { full_name: "黄太太", avatar_url: null },
  },
  {
    id: "review-wu-6",
    order_id: "order-wu-6",
    user_id: "user-wu-6",
    master_id: "wu-yang",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Comprehensive life path analysis",
    content: "Master Wu provided a thorough BaZi analysis covering career, relationships, and health. His 12+ years of experience shows in the depth of his insights. The consultation was well worth the investment.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-05T11:00:00Z",
    user: { full_name: "Robert Zhang", avatar_url: null },
  },

  // ========== Master Luna (6 reviews) ==========
  {
    id: "review-luna-1",
    order_id: "order-luna-1",
    user_id: "user-luna-1",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Tarot revealed my true feelings",
    content: "I was confused about a relationship and Master Luna's tarot reading helped me see what my heart already knew but my mind was avoiding. Her intuitive insights were spot on and helped me make a decision I was avoiding.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-03-12T19:00:00Z",
    user: { full_name: "Amanda S.", avatar_url: null },
  },
  {
    id: "review-luna-2",
    order_id: "order-luna-2",
    user_id: "user-luna-2",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Career clarity through the cards",
    content: "Master Luna used tarot to help me understand my career path. The reading revealed opportunities I hadn't considered and confirmed my instincts about leaving a toxic work environment. Now I'm in a much better place professionally.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-28T15:30:00Z",
    user: { full_name: "James Chen", avatar_url: null },
  },
  {
    id: "review-luna-3",
    order_id: "order-luna-3",
    user_id: "user-luna-3",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Guidance during a difficult transition",
    content: "当我面临人生重大转折时，卢娜师傅的塔罗解读给了我希望和方向。她看到的不仅是当前的困难，还有未来的可能性。她的解读温柔而有力，让我重新找回了前进的勇气。",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-15T20:00:00Z",
    user: { full_name: "林小姐", avatar_url: null },
  },
  {
    id: "review-luna-4",
    order_id: "order-luna-4",
    user_id: "user-luna-4",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Monthly readings keep me aligned",
    content: "I've been having monthly sessions with Master Luna for half a year now. Her tarot readings help me stay aligned with my true path and navigate challenges with grace. She's like a spiritual compass in my life.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-02-01T18:30:00Z",
    user: { full_name: "Michelle Wang", avatar_url: null },
  },
  {
    id: "review-luna-5",
    order_id: "order-luna-5",
    user_id: "user-luna-5",
    master_id: "master-luna",
    overall_rating: 5,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 5,
    title: "Love and relationship insights",
    content: "卢娜师傅帮我看清了一段纠结很久的感情。她的塔罗牌不仅显示了现状，还指出了我需要学习的课题。现在我明白了什么是真正适合我的关系，感谢她的指引！",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-20T14:00:00Z",
    user: { full_name: "周女士", avatar_url: null },
  },
  {
    id: "review-luna-6",
    order_id: "order-luna-6",
    user_id: "user-luna-6",
    master_id: "master-luna",
    overall_rating: 4,
    accuracy_rating: 5,
    communication_rating: 5,
    value_rating: 4,
    title: "Intuitive and empowering",
    content: "Master Luna has a rare gift of combining intuition with practical guidance. Her readings don't just tell you what's happening - they empower you to take control of your destiny. Highly recommended for anyone seeking clarity.",
    is_anonymous: false,
    status: "approved",
    created_at: "2026-01-10T16:45:00Z",
    user: { full_name: "Thomas Lee", avatar_url: null },
  },
];