-- 安全清理所有 Stellawei 表（按依赖顺序逆序删除）

DROP TABLE IF EXISTS order_status_history CASCADE;
DROP TABLE IF EXISTS refund_requests CASCADE;
DROP TABLE IF EXISTS user_communication_settings CASCADE;
DROP TABLE IF EXISTS chat_events CASCADE;
DROP TABLE IF EXISTS api_durations CASCADE;
DROP TABLE IF EXISTS message_read_status CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS master_time_slots CASCADE;
DROP TABLE IF EXISTS master_schedule_exceptions CASCADE;
DROP TABLE IF EXISTS master_schedules CASCADE;
DROP TABLE IF EXISTS master_services CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS review_likes CASCADE;
DROP TABLE IF EXISTS review_replies CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS user_settings CASCADE;
DROP TABLE IF EXISTS masters CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS service_tiers CASCADE;
DROP TABLE IF EXISTS tarot_cards CASCADE;
DROP TABLE IF EXISTS app_configs CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 删除自定义类型
DROP TYPE IF EXISTS order_status CASCADE;
DROP TYPE IF EXISTS order_type CASCADE;
DROP TYPE IF EXISTS communication_method_type CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS payment_status CASCADE;

SELECT 'Cleanup complete' as status;
